use_frameworks!

platform :ios, '8.0'

target 'MessageKit_Example' do
  pod 'MessageKit', :path => '../'

  target 'MessageKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
